### ISSUE TITLE
Feature request: Add syntax for ComfyUI_Cutoff functionality

### ISSUE THREAD

**Issue by TimmermanV** [BlenderNeko/ComfyUI_ADV_CLIP_emb#10]
I've been trying out ComfyUI_Cutoff and I like what it can do. It does require quite a lot of extra nodes and connections. I was wondering if it would be possible for the Advanced CLIP Text Encode node to be extended with a syntax that would allow automatic generation of these cutoff regions under the hood. This would make it much faster and easier to work with.

For example, if you could write `a cute girl, white>shirt with green>tie, red>shoes, blue>hair, yellow>eyes, pink>skirt` instead of creating a Cutoff Set Regions node for each of those. And perhaps the weights could be in there as well in some way?

**Comment by BlenderNeko** [comment]
You don't need a set Region for each, you can put multiple regions in a single node. I currently have no plans for adding custom syntax.

**Comment by TimmermanV** [comment]
Thanks for the additional explanation. I did read that, but it wasn't yet clear to me that tokens in the target_text could each refer to a different region in region_text. Great to see that actually works, thanks!
