### ISSUE TITLE
Feature request - add Comfy's older clip method as option

### ISSUE THREAD

**Issue by JorgeR81** [BlenderNeko/ComfyUI_ADV_CLIP_emb#14]
Hi, 
I have 2 Comfy UI portable installs, one one from yesterday, another from a month ago. I didn't use the automatic update option.
( In the older Comfy, your nodes, which I downloaded yesterday, were not working. In the new Comfy they work, so it's OK. 
The A1111 weight interpretation method seems to work really well ).
 
But, I also noticed that the 2 Comfy installs give different results, even when no custom nodes are used. The weight interpretation seemed to be different, based on my previous tests. 
So I checked the new commits, and this seems to be the cause:
"**CLIP code refactor and improvements**"
https://github.com/comfyanonymous/ComfyUI/commit/656c0b5d90239efb8be4281d2c16d52ca722064c

This new method seems to be better, but I also like the old one. 
I only plan to use the A1111 method on specific cases, to replicate the style of other images.
Also, all my previous images are fine tuned on the old Comfy method, and I can't replicate the old look, especially when complex negative prompts are used. 

Could it be possible to add the old Comfy method as an option, in the "_weight_interpretation_" parameter of the "_BNK_CLIPTextEncodeAdvanced_" node.
This way I don't have to keep both Comfy installs.
Thanks

**Comment by BlenderNeko** [comment]
Doesn't look like any of the actual weighting has changed. The code you linked only contains optimizations and no actual behavioral changes. If you see differences in generation between comfy versions it is more likely to originate from a different part in the code.

**Comment by JorgeR81** [comment]
I've started a discussion on the Comfy UI page to see if they know what's going on.
I've added some pictures. 
The new version seemed to work better with some flatter (retro) anime checkpoints, but on the more realistic ones, not so much.
( I hope it's just just some setting I've accidentally changed, or something )

https://github.com/comfyanonymous/ComfyUI/discussions/1981

**Comment by JorgeR81** [comment]
So it was my fault, after all.
I forgot I didn't have the easynegative embedding in the November version ! 
I added it and now both versions look identical ( like, pixel by pixel ! ).
You're all very kind, and helpful. I feel bad about wasting your time!
