### ISSUE TITLE
CLIP Text Encode (Advanced) Suddenly Throwing Errors

### ISSUE THREAD

**Issue by Kinglord** [BlenderNeko/ComfyUI_ADV_CLIP_emb#2]
I'm not sure what I did but suddenly one of my advanced clip nodes started throwing an error in the console and killing the job. I think it has something to do with the length of my prompt but I'm not sure, there's a lot of what I think is useless spam but the final line has what I think is causing the problem.

`RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 2464 but got size 308 for tensor number 1 in the list.`

I'm going to swap back over to the default CLIP node since it works fine with the same prompt for now but hopefully I can get things sorted.

**Comment by BlenderNeko** [comment]
What settings and prompt did you use?

**Comment by BlenderNeko** [comment]
>  there's a lot of what I think is useless spam but the final line has what I think is causing the problem.

that useless spam is probably also very helpful for me to track down the issue

**Comment by Kinglord** [comment]
Sure thing, here's the full error log. I'll post my prompt under it that broke it, I had the same thing happen to another prompt as soon as I added some weights to something so I think it's related to the number of terms I have weighted?
`Traceback (most recent call last):
  File "X:\BOS\WD_Gen\ComfyUI\ComfyUI\execution.py", line 184, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "X:\BOS\WD_Gen\ComfyUI\ComfyUI\execution.py", line 60, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "X:\BOS\WD_Gen\ComfyUI\ComfyUI\execution.py", line 60, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "X:\BOS\WD_Gen\ComfyUI\ComfyUI\execution.py", line 69, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "X:\BOS\WD_Gen\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\nodes.py", line 19, in encode
    embeddings_final = advanced_encode(clip, text, token_normalization, weight_interpretation, w_max=1.0)
  File "X:\BOS\WD_Gen\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\adv_encode.py", line 193, in advanced_encode
    return advanced_encode_from_tokens(clip, tokenized, token_normalization, weight_interpretation, w_max)
  File "X:\BOS\WD_Gen\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\adv_encode.py", line 183, in advanced_encode_from_tokens
    weighted_emb = from_masked(unweighted_tokens, weights, word_ids, weighted_emb, clip)
  File "X:\BOS\WD_Gen\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\adv_encode.py", line 87, in from_masked
    embs = batched_clip_encode(masked_tokens, clip, len(tokens))
  File "X:\BOS\WD_Gen\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\adv_encode.py", line 54, in batched_clip_encode
    embs = torch.cat(embs)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 2464 but got size 154 for tensor number 1 in the list.`

Prompt:
`1girl, (detailed face), (detailed eyes), best quality, hyper detailed, masterpiece, (mature Swedish woman), Freya Adelsköld, techwear, (mecha musume:.75), (himedere), aloof, short hair, multicolored hair, (platinum blonde hair), white inner hair, (grey eyes:1.35), thick lips, upturned nose, eyelashes, looking at viewer, highest details, luminous eyes, tall, medium breasts, tough, (pale skin), oval face, regal armor, light rays, (high contrast), (colorful), simple background, trending on artstation, detailed, award winning illustration, hd, 4k, digital art, cinematic lighting,`

I tried all the various settings and they all seemed to give the same error. The one I'm using most though is length+mean and comfy++

Let me know if I can help send anything else.
