### ISSUE TITLE
SDXL model throws out clip_layer errors after ComfyUI commit c2cb8e8 (Feb 25, 2024)

### ISSUE THREAD

**Issue by SakanakoChan** [BlenderNeko/ComfyUI_ADV_CLIP_emb#20]
After ComfyUI commit `c2cb8e8` all of the clip text encode nodes provided in this extension don't work for SDXL models, but SD1.5 models still go fine. Error trace back is as follows:

`
Error occurred when executing BNK_CLIPTextEncodeAdvanced:

'SDXLClipModel' object has no attribute 'clip_layer'

File "D:\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\nodes.py", line 21, in encode
embeddings_final, pooled = advanced_encode(clip, text, token_normalization, weight_interpretation, w_max=1.0, apply_to_pooled=affect_pooled=='enable')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\adv_encode.py", line 246, in advanced_encode
embs_l, _ = advanced_encode_from_tokens(tokenized['l'],
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\adv_encode.py", line 187, in advanced_encode_from_tokens
base_emb, pooled_base = encode_func(unweighted_tokens)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\adv_encode.py", line 249, in
lambda x: encode_token_weights(clip, x, encode_token_weights_l),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\adv_encode.py", line 226, in encode_token_weights
model.cond_stage_model.clip_layer(model.layer_idx)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\.ext\Lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
`

### **I believe this is because the "Clip Set Last Layer" node conflicts with this custom node when using XL models after the commit. When I bypassed "Clip Set Last Layer" node, everything went well.**

Below is the screenshot of my workflow

![image](https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb/assets/148366895/9e9aea63-f1db-4b4e-a501-f43160c4b6fd)

Thank you for reading this, if you could help fix this issue i would be super grateful!

**Comment by Philmar1986** [comment]
I have the same issue

**Comment by RYG81** [comment]
yes having same issue for me too, any solution?

**Comment by SakanakoChan** [comment]
A current solution is to change to another custom node called "Efficient Loader" which is also a custom node made by BlenderNeko (BNK, the author of the node here). Efficient Loader also has a changeable property weight_interpretation which can do the same (switch between comfy and A1111 mode) as the node here, and it's **already compatible with the latest comfyui version**.

**Comment by BTSpaniel** [comment]
Found a Alternative: https://github.com/CosmicLaca/ComfyUI_Primere_Nodes?tab=readme-ov-file#special-features-in-attached-most-complex-workflow-primere_latest_workflowjson

![chrome_RYVfxid417](https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb/assets/18719511/eb14ad19-42aa-42fa-84e8-db78e335ea51)

**Comment by hike2008** [comment]
I have fork and fix the problem here：

https://github.com/hike2008/ComfyUI_ADV_CLIP_emb

or else can fix yourself like this：
![CleanShot 2024-03-13 at 16 12 31@2x](https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb/assets/8948629/1ec5be2c-1a18-48e6-acdc-4e2ec27ef017)
