### ISSUE TITLE
Does BNK_CLIPTextEncodeAdvanced parse the prompts 'exactly' like A1111?

### ISSUE THREAD

**Issue by 2kpr** [BlenderNeko/ComfyUI_ADV_CLIP_emb#7]
Excuse me for not having looked through your code in it's entirety, but I had a quick question...

Does BNK_CLIPTextEncodeAdvanced parse the prompts 'exactly' like A1111?
See here: [https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/prompt_parser.py](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/prompt_parser.py)

I only ask because even though I'm using the ComfyUI GPU noise custom nodes, and BNK_CLIPTextEncodeAdvanced, when I'm doing things in my positive/negative prompts involving many nested (), it seems it's not having the same effects as in A1111.

Any help is appreciated, thanks!

**Comment by BlenderNeko** [comment]
No I don't think it does. The parsing is left to comfy. One way in which the A1111 and comfy parsers differ is that in comfy, literals override nesting. So in prompt `((a:0.5)b:2.0)` `a` in comfy will remain at 0.5, wil in A1111 it wil become 1.0

**Comment by 2kpr** [comment]
That explains/solves it, thanks, great work btw! :)

**Comment by andupotorac** [comment]
@BlenderNeko why does a become 1? Not sure I understood from your example.
