### ISSUE TITLE
All options generate the same image

### ISSUE THREAD

**Issue by davemedvitz** [BlenderNeko/ComfyUI_ADV_CLIP_emb#9]
I'm having a hard time using this - or maybe I have an improper understanding of what this is supposed to do.

I have a prompt.  It is made of just keywords and weights, there is not extensions, loras, controlnets, etc.  Using this prompt, I generate two different images in Comfy and A1111.  I then replace the standard prompt widget with this one.  Every image I create ends up producing the same images, regardless of the options for weight composition and normalization.

Is there a test prompt, possibly with result images, that can be used to verify that I'm doing things correctly?

I've included an image from both systems.  The ComfyUI workflow includes generating both two images, once with the built in prompt widget, and once with the Advanced widget configured for A1111.  Would appreciate any help in understanding my results.

![00012-595228454217178](https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb/assets/42068562/275c3193-7b6c-4630-8117-abd436feff9a)
![ComfyUI_temp_zymvm_00003_](https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb/assets/42068562/7e7b1340-be77-4e4b-90bf-b5f1c9f9975c)

**Comment by davemedvitz** [comment]
And as a side note, I have verified xformers enabled in both systems.

**Comment by davemedvitz** [comment]
Thank you for this.  I am now getting different images in Comfy using comfy and a1111 prompts.  But I'm still not able to get A1111 and comfy with a1111 prompts to get close.  I'll keep playing with it, though.

I'm still seeing same images, though, when I'm using the same prompt with comfy and compel (trying to come close to some of my images created with InvokeAI).

**Comment by BlenderNeko** [comment]
comfy generates its noise by default on the CPU rather than GPU, there might also be differences in implementation details in any of the SDE and ancestral samplers. As for compel, my implementation of compel isn't faithful to the original compel library, so i'm not sure if you can actually reproduce Invoke outputs with that.
